# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGU3uuWTe7by6d-YJVvw3CCC73Ij3TPN
"""

import pandas as pd
df = pd.read_csv("WHO COVID-19 cases.csv")
Brazil_data = df[df["Country"] == "Brazil"]
print(Brazil_data)